services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-prod
    container_name: backend-prod
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:root@postgres/backend
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres-prod
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-prod
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
